# NginxFlow 主配置
load_module /usr/lib/nginx/modules/ngx_stream_module.so;

user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;
    keepalive_timeout 65;
    client_max_body_size 64m;
    log_format combined_custom '$remote_addr - [$time_local] "$request" '
                               '$status $body_bytes_sent "$http_referer" "$http_user_agent"';

    # NginxFlow Web UI
    server {
        listen 9001 default_server;
        root /opt/nginxflow/frontend/dist;
        index index.html;
        location / { try_files $uri $uri/ /index.html; }
        location /api/ {
            proxy_pass http://127.0.0.1:9000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }

    include /etc/nginx/conf.d/*-http.conf;
}

stream {
    log_format basic '$remote_addr [$time_local] '
                     '$protocol $status $bytes_sent $bytes_received '
                     '$session_time "$upstream_addr"';
    include /etc/nginx/conf.d/*-stream.conf;
}
